# Generated by Django 3.1.7 on 2021-04-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20210406_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('n', 'None'), ('u', 'Under_behandling'), ('a', 'Afgjort'), ('i', 'ignored')], max_length=1),
        ),
    ]
