# Generated by Django 3.1.7 on 2021-04-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20210406_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseinfo',
            name='caseworker',
        ),
        migrations.RemoveField(
            model_name='caseinfo',
            name='company',
        ),
    ]
