# Generated by Django 3.1.7 on 2021-04-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20210407_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='name',
            new_name='filename',
        ),
    ]
