# Generated by Django 3.1.7 on 2021-04-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_media_time_of_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
