# Generated by Django 3.1.7 on 2021-04-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20210407_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='time_of_delete',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
