# Generated by Django 3.1.7 on 2021-04-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20210411_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_case_info', to='case.caseinfo'),
        ),
        migrations.AlterField(
            model_name='media',
            name='case_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_case_info', to='case.caseinfo'),
        ),
    ]
