# Generated by Django 3.1.7 on 2021-04-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_auto_20210413_0437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JudgeDetail',
        ),
    ]
