# Generated by Django 3.1.7 on 2021-04-19 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseworker', '0002_auto_20210416_0026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0016_auto_20210417_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinfo',
            name='caseworker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='caseworker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseinfo',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='caseworker.company'),
            preserve_default=False,
        ),
    ]
