# Generated by Django 3.1.7 on 2021-04-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caseworker', '0002_auto_20210416_0026'),
        ('case', '0018_auto_20210419_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='caseworker.company'),
            preserve_default=False,
        ),
    ]
