# Generated by Django 3.1.7 on 2021-04-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0019_auto_20210419_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='caseworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='caseworker', to=settings.AUTH_USER_MODEL),
        ),
    ]
