name: Whistle_blower stories
on:
  push:
    branches: [ 'story*', 'feature*' ]
  pull_request:
    branches: [ 'story*', 'feature*' ]
jobs:
  test:
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DEBUG_VALUE: ${{ secrets.DEBUG_VALUE }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are syntax errors in case or caseworker
          flake8 case --count --select=E9,F4,F6,F8 --show-source --statistics
          flake8 caseworker --count --select=E9,F4,F6,F8 --show-source --statistics
      - name: Unittest
        run: |
          python3 manage.py test case
          python3 manage.py test caseworker
          coverage run manage.py test case
          coverage report
          coverage run manage.py test caseworker
          coverage report