name: Whistle_blower stories
on:
  push:
    branches: [ 'story*', 'feature*' ]
  pull_request:
    branches: [ 'story*', 'feature*' ]
jobs:
  unit-integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_HOST:  ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT}}
      DB_USER: ${{ secrets.DB_USER}}
      DEBUG_VALUE: ${{ secrets.DEBUG_VALUE}}
      ALLOWED_HOSTS: '*'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      FEATURES: '{ "REVISIT_CASE": true, "EDIT_CASE": true }'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 case --count --select=E9,F4,F6,F8 --show-source --statistics
          flake8 caseworker --count --select=E9,F4,F6,F8 --show-source --statistics
      - name: Migrate database
        run: |
          python manage.py migrate
      - name: Run pytest
        run: |
          pytest
